[phases.setup]
nixPkgs = ["nodejs_20", "pnpm", "openssl"]

[phases.install]
cmds = ["pnpm i --frozen-lockfile --prod=false"]

[phases.build]
cmds = ["pnpm run build:railway"]

[start]
cmd = "node artifacts/api-server/dist/index.mjs"
