import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import documentsRouter from "./documents";
import authRouter from "./auth";
import usersRouter from "./users";
import salesLeadsRouter from "./sales-leads";
import customersRouter from "./customers";
import vendorsRouter from "./vendors";
import productsRouter from "./products";
import taxRatesRouter from "./tax-rates";
import quotesRouter from "./quotes";
import estimatesRouter from "./estimates";
import invoicesRouter from "./invoices";
import purchaseOrdersRouter from "./purchase-orders";
import billsRouter from "./bills";
import inventoryRouter from "./inventory";
import shipmentsRouter from "./shipments";
import expensesRouter from "./expenses";
import bankAccountsRouter from "./bank-accounts";
import accountingRouter from "./accounting";
import dashboardRouter from "./dashboard";
import auctionsRouter from "./auctions";
import inventoryLocationsRouter from "./inventory-locations";
import easyshipRouter from "./easyship";
import appSettingsRouter from "./app-settings";
import returnsRouter from "./returns";
import plaidRouter from "./plaid";
import ticketsRouter from "./tickets";
import paymentsRouter from "./payments";

const router: IRouter = Router();
router.use(storageRouter);
router.use(documentsRouter);

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(salesLeadsRouter);
router.use(customersRouter);
router.use(vendorsRouter);
router.use(productsRouter);
router.use(taxRatesRouter);
router.use(quotesRouter);
router.use(estimatesRouter);
router.use(invoicesRouter);
router.use(purchaseOrdersRouter);
router.use(billsRouter);
router.use(inventoryRouter);
router.use(shipmentsRouter);
router.use(expensesRouter);
router.use(bankAccountsRouter);
router.use(accountingRouter);
router.use(dashboardRouter);
router.use(auctionsRouter);
router.use(inventoryLocationsRouter);
router.use(easyshipRouter);
router.use(appSettingsRouter);
router.use(returnsRouter);
router.use(plaidRouter);
router.use(ticketsRouter);
router.use(paymentsRouter);

export default router;
